name: deploy-book
run-name: Building and deploying Jupyter-Book
# Run this when the master or main branch changes
on: [push]
permissions:
  contents: write
# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
      - name: pip-install Jupyter Book
        run: |
          pip install jupyter-book sphinx-proof ghp-import
      - name: Build the book
        run: |
          jupyter-book build .
      - name: Push to github-pages branch
        run: |
          ghp-import -n -p -f _build/html
#- name: Upload artifact
      #  uses: actions/upload-pages-artifact@v3
      #  with:
      #    path: "_build/html"
      